### ISSUE TITLE
Backspace animation

### ISSUE THREAD

**Issue by Jezwin** [ratson/react-typist-loop#2]
Is there a way the backspace animation could be added, so that on word replacement it doesn't remove the entire word at once instead show some backspace animation?

**Comment by sauhard98** [comment]
That can be implemented with the currently as well.
Example in the given implementation:
```javascript
<TypistLoop interval={1000}>
    {[ 'Hello World', 'Good Morning', 'Bye', ].map(text => 
        <Typist key={text} startDelay={0}>{text}
            <Typist.Backspace count={text.length} delay={100} />
        </Typist>)}
</TypistLoop>
```

**Comment by Jezwin** [comment]
Hey thanks, that works!
